document.getElementById("generateFile").addEventListener("click", function () {
  // Define the content of the new HTML file
  const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Generated HTML Page</title>
    </head>
    <body>
      <h1>This page was generated by JavaScript!</h1>
      <p>You can add more content here.</p>
    </body>
    </html>
  `;

  // Create a Blob object with the HTML content
  const blob = new Blob([htmlContent], { type: "text/html" });

  // Create a download link
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "generatedPage.html"; // The name of the file to download

  // Append the link to the body, click it to trigger download, and remove it
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
});
